services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "127.0.0.1:5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    driver: local
    driver_opts:
      type: none
      device: ./n8n_data
      o: bind